### ISSUE TITLE
[Kiss Comic readcomiconline] Connector not working

### ISSUE THREAD

**Issue by kolbdog3333** [manga-download/hakuneko#5015] opened 2022-09-27 19:04 UTC
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
No mangas are showing when doing the update but there are mangas on the website
**To Reproduce**
1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by MikeZeDev** [comment] 2022-09-29 18:03
Duplicate of https://github.com/manga-download/hakuneko/issues/4958
Already fixed by a PR.

**Closed as not planned** 2022-10-22 20:49 UTC
Labels: Duplicate
