### ISSUE TITLE
[<ZeroScans>] Connector not working

### ISSUE THREAD

**Issue by Murshid7absi** [manga-download/hakuneko#6432] opened 2023-11-15 16:38 UTC
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

When refreshing the connector it shows the below error:
![image](https://github.com/manga-download/hakuneko/assets/95138799/304fe9f6-350d-40b4-8de8-7d070d6332ce)

the new chapters are coming but don't load fast or the download fails and brings the error "failed to fetch"
![image](https://github.com/manga-download/hakuneko/assets/95138799/4775d989-50f3-4d79-a31e-cd33920d2ec8)
![image](https://github.com/manga-download/hakuneko/assets/95138799/8438450c-15a5-43ca-ba08-4ef44340ee9e)

The URL has been changed to https://zeroscans.com/comics instead of https://zeroscans.com/swordflake/comic in the website (idk just assuming)
![image](https://github.com/manga-download/hakuneko/assets/95138799/433988e4-71e8-496a-b467-69d824763e93)
![image](https://github.com/manga-download/hakuneko/assets/95138799/4fa70dec-187f-47ef-a35e-1a72040e9d89)

### To Reproduce

1. ZeroScans
2. Refresh connector

**Comment by MikeZeDev** [comment] 2023-11-15 17:59
1) This is not what you think. The url you mentioned as invalid is **valid** we fetch JSON data using their API, not a web page.

![image](https://github.com/manga-download/hakuneko/assets/10671518/455c8102-a603-491a-bef3-51df4ef8e7ec)

2) I couldnt reproduce your error but seeing you got error 429 and a bunch of download chapter i supposed you used Haku for mass downloading and website blocked you. Error 429 is typical in that case.

Retry tomorrow or try with a vpn to change IP.

If its fixed, you should close this ticket, if error persist tell us.

**Comment by Murshid7absi** [comment] 2023-11-15 18:50
Thanks for the reply.. I'll try that.

**Closed as not planned** 2023-12-01 17:22 UTC
Labels: Can't reproduce bug
