### ISSUE TITLE
[KomikAV] Connector not working

### ISSUE THREAD

**Issue by Shaft14** [manga-download/hakuneko#5057] opened 2022-10-12 01:43 UTC
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes/No

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes/No

**Describe the bug**

**To Reproduce**
1. KomikAV
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
![image](https://user-images.githubusercontent.com/112748173/195229524-af7ebc45-b962-4b98-acd9-da26f324e2ae.png)
![image](https://user-images.githubusercontent.com/112748173/195229573-a9847bae-3873-4a9c-9d02-e2ec590045b9.png)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]
 -

**Comment by MikeZeDev** [comment] 2022-10-12 10:21
Cloudflare error on https://komikav.com/manga/list-mode/

Cant pass "Checking if connexion is secure" on Webview.

**Comment by MikeZeDev** [comment] 2022-10-20 12:49
Duplicate of https://github.com/manga-download/hakuneko/issues/4947.

**Comment by Shaft14** [comment] 2022-10-26 07:35
caan use this https://komikav.com/manga/ ?

**Closed as not planned** 2022-11-03 21:05 UTC
Labels: Duplicate
