### ISSUE TITLE
[Site Request] Manhwa Freak

### ISSUE THREAD

**Issue by Infernotez** [manga-download/hakuneko#4854] opened 2022-07-23 13:29 UTC
**Name of the website**
Manhwa Freak

**Website urls (examples below)**
- Site: https://manhwafreak.com/
- Manga example: https://manhwafreak.com/manga/i-was-born-as-the-seventh-prince-what-should-i-do/
- Chapter online viewer example: https://manhwafreak.com/i-was-born-as-the-seventh-prince-what-should-i-do-ch-01/
- 
**Languages**
English

**Comment by MikeZeDev** [comment] 2022-11-17 18:57
Duplicate of https://github.com/manga-download/hakuneko/issues/4649

**Closed as not planned** 2022-11-17 20:19 UTC
Labels: Duplicate
