### ISSUE TITLE
[Reaper] Connector not working

### ISSUE THREAD

**Issue by tsentered** [manga-download/hakuneko#6211] opened 2023-09-07 02:08 UTC
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Downloads aren't working

### Describe the bug

Everything works except for downloading the chapters. Looking up existing cases it seems that there were a couple open cases which seem from long ago and I know it worked post date of those cases. I didn't run into cloudfare verification.

### To Reproduce

1. Name of connector - ReaperScans
2. Name of manga (if connector update is working)-All
3. Name of chapter (if manga update is working)-All
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)
<img width="1115" alt="Screenshot 2023-09-06 at 6 56 27 PM" src="https://github.com/manga-download/hakuneko/assets/70929406/0915ca20-9aea-4c2c-b6f9-c5a9d4d5114f">
<img width="1111" alt="Screenshot 2023-09-06 at 6 56 57 PM" src="https://github.com/manga-download/hakuneko/assets/70929406/c240490c-30f6-40d9-ba02-c6e7d0f7533b">
<img width="1331" alt="Screenshot 2023-09-06 at 6 59 10 PM" src="https://github.com/manga-download/hakuneko/assets/70929406/833f32c0-6ef1-4b31-9d7e-e3d388a9012b">

**Comment by MikeZeDev** [comment] 2023-09-07 08:02
1) You are checking bookmarks. They could become outdated if website change, dont rely on bookmarks to tell if something doesnt work ;)

2) Its ReapersScans, not just "reaper" and there are plenty of "reaperscans" websites. If you want help please name the exact website, it will save time for the people helping. If you are too lazy to type the entire name i may be too lazy to check whats going on :D

3) Cloudflare TAG . Cloudflare problem isnt solvable. Its even stated in the opened issue you found. It doesnt matter how many issues people will open it wont change. Issue will just end closed as duplicate (especially for RS) or stay opened for reference. Its just wasting time for everyone :(

4) Maybe the template isnt clear enough :  "Searching for existing issues" means "Dont open another if the problem is already known". Because it will just clog the repository. I guess we should have made things clearer, sorry about that.

Duplicate https://github.com/manga-download/hakuneko/issues/5488

**Closed as not planned by MikeZeDev** 2023-09-07 08:02 UTC
Labels: Duplicate

**Comment by tsentered** [comment] 2023-09-08 01:02
Hello,

Thank you for the quick response. I’ll respond to each items in order.

1. I don’t do refresh from bookmark. I check direct. I took the snapshot simply to demonstrate that the chapter list is coming up. As I had mentioned the refresh works fine.

2. Apologies, I’ll use the full name from now on. That definitely was lazy of me.

3. I mentioned that the date that issue was created  was outdated. Connector was working fine for quite some time after that issue was created. That’s why I made the point to clarify that point and took the screen shot to show the I  did actually look. The connector stopped working just a month ago and as the screenshot showed there was no cloudfare on the site. I went through without a cloud fare check.

4. As mentioned the issues were outdated and while open the connector was working for quite some time after the open issue was created.


No matter what, you have my gratitude for responding and I understand that it’s definitely a pain but you all still do this stuff which is what makes you all awesome. 

So again, thank you.

**Comment by MikeZeDev** [comment] 2023-09-08 11:14
Its ok :) .

Just to clarify: there is no "outdated" issue. If its open you can consider the problem is still happening, unless it fixed itself and we doesnt know. As for Cloudflare, it can be activated or desactivated by the website owner, and it has different levels, so it "may fix itself" without us knowing. Because people never come to say "its fixed" the issue stay opened ;)

Sorry about not being able to fix this, have a nice day.
