### ISSUE TITLE
[Site Request] Ichijinsha (Zero Sum)

### ISSUE THREAD

**Issue by westward-MARTIAN** [manga-download/hakuneko#3158] opened 2021-03-04 05:15 UTC
**Name of the website**
一迅社WEB (Ichijinsha)

**Website urls (examples below)**
- Site: https://online.ichijinsha.co.jp/zerosum
- Manga List: https://online.ichijinsha.co.jp/zerosum/works
- Manga example: https://online.ichijinsha.co.jp/zerosum/comic/musikaburihime
- Chapter online viewer example: https://static.ichijinsha.co.jp/online/books/zerosum/rasutame/rasutame_SUDtZWAt001/index.html

**Languages**
japanese

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
uses speedbinb

**Comment by Ever4engel** [comment] 2021-03-11 11:54
duplicate of #1356

**Closed as completed** 2021-03-11 11:56 UTC
Labels: Duplicate
