### ISSUE TITLE
[9Anime] Connector not working

### ISSUE THREAD

**Issue by I-JMC** [manga-download/hakuneko#6053] opened 2023-07-20 09:08 UTC
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
- Yes

**Did you [try Nightly Build](https://github.com/manga-download/hakuneko/releases) ?**
- Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
- Yes

**Describe the bug**
9Anime doesn't work in Nightly, but it works in Stable (I think)

**To Reproduce**
1. 9Anime
2. ![image](https://github.com/manga-download/hakuneko/assets/99205448/65c2a507-2eb5-42ce-81eb-a2ff87c4ca74)

**Screenshots**
![image](https://github.com/manga-download/hakuneko/assets/99205448/943fdfaf-c51c-4335-9ef7-9e62048c836d)

**HakuNeko (please complete the following information):**
 - Version 8.3.4 Nightly Portable

**Comment by MikeZeDev** [comment] 2023-07-20 12:18
I got the error on first try and now i cant reproduce it. Also 9Anime code is same on stable and nightly right now.
Thats weird. There is a "security check" on homepage. 🤔 

Maybe you can try opening website homepage (top right button)
![image](https://github.com/manga-download/hakuneko/assets/10671518/8e3a3381-7402-48a1-a1b9-31fd04b73c99), close it, and try to fetch "manga list" again 🤷 

Also makes sure you use filemoon or streamsb for episodes (in case you can see episodes after)

**Comment by I-JMC** [comment] 2023-07-20 12:57
Yeah, that's what I did the first time, now it works 🤷‍♂️

**Closed as completed** 2023-07-20 12:58 UTC
Labels: Website Change

**Comment by I-JMC** [comment] 2023-07-20 13:00
> Also makes sure you use filemoon or streamsb for episodes (in case you can see episodes after)

Also, why don't the other ones work ?

**Comment by MikeZeDev** [comment] 2023-07-21 10:50
Basically, video hosters dont want people to download. "WATCH MY ADS". They take security measures.

* The video player we use is technically limited, we cant fool the websites
* No other video players got that feature anyway. They wont code it because they target real browsers and real browsers doesnt allow what we need afaik. 
* And guess what, we lack time to do that ourselves.

This affect previewing and downloading, because the problem is accessing the "playlist segments files" on the server.
Everything can be done manually but it wont work for previewing anyway and WE HAVE OTHER PRIORITIES ATM
