### ISSUE TITLE
Delitoon Connector not working

### ISSUE THREAD

**Issue by Pipixel** [manga-download/hakuneko#5296] opened 2022-12-30 13:49 UTC
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
No and Yes

**Describe the bug**
After the website update, it's broken the plugin, the refresh and links which been updated

**To Reproduce**
1. Select Delitoon plugin
2. Try to refresh the library or login with the plugin link

**Screenshots**

![hakuneko_350C9vHenX](https://user-images.githubusercontent.com/66361896/210076934-9e7d15b4-3a65-462b-84ed-7bb5eea2a70b.png)

**HakuNeko (please complete the following information):**
 - Version 6.17

**Comment by MikeZeDev** [comment] 2022-12-30 16:23
duplicate of https://github.com/manga-download/hakuneko/issues/4988, and its probably fixed by https://github.com/manga-download/hakuneko/pull/5225

**Closed as not planned** 2022-12-30 16:23 UTC
Labels: Duplicate
