### ISSUE TITLE
[Site Request] Mangaowl

### ISSUE THREAD

**Issue by altslayer** [manga-download/hakuneko#4340] opened 2022-01-25 05:23 UTC
**MangaOwl**
thewebsitename

**Website urls**
- Site: https://mangaowls.com/
- Manga example: https://mangaowls.com/single/57262/bj-alex

**Languages**
English

**Comment by manh21** [comment] 2022-01-26 15:39
Duplicate of #2335

**Closed as completed** 2022-03-07 22:48 UTC
Labels: Duplicate
