### ISSUE TITLE
9anime

### ISSUE THREAD

**Issue by AdriBD83** [manga-download/hakuneko#4626] opened 2022-04-29 10:20 UTC
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
the episodes doesn't loads properly.

**To Reproduce**
1. nineanime
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Comment by MikeZeDev** [comment] 2022-12-30 17:51
Duplicate of https://github.com/manga-download/hakuneko/issues/4561

**Closed as not planned** 2022-12-30 17:51 UTC
Labels: Duplicate
