### ISSUE TITLE
[Feature] throttle option for CR manga

### ISSUE THREAD

**Issue by stark700** [manga-download/hakuneko#2417] opened 2020-10-09 06:27 UTC
Crunchyroll rate limits if you send too many requests in a short period of time. I would like the ability to download pages individually and with a short custom delay inbetween to get around this.

I downloaded 3 chapters today, and got rate limited.

Would recommend adding this option to throttle/delay for Viz and Mangaplus as well. I have gotten rate limited by Viz before too

HakuNeko Version 6.17

**Comment by newaccforhc** [comment] 2020-10-10 07:53
Issue is duplicate of #2275 

VIZ already has throttle option.. increase the value if you're getting rate-limited..

Mangaplus doesn't rate limit afaik... no need to add for that..


I'll leave it upto @ronny1982 or @Sheepux to decide whether to close it or not..

**Closed as completed** 2020-10-10 19:36 UTC
Labels: Duplicate
