### ISSUE TITLE
[Site Request] Tappytoon.com

### ISSUE THREAD

**Issue by snickerdooodle45** [manga-download/hakuneko#2154] opened 2020-08-08 15:18 UTC
**Name of the Website**
Tappytoon.com

**Website urls (examples below)**
- Site: https://www.tappytoon.com/en/
- Manga List: https://www.tappytoon.com/en/genres?alias=romance
- Manga example: https://www.tappytoon.com/en/comics/i-bid-you-adieu
- Chapter online viewer example: https://www.tappytoon.com/en/chapters/931270901?

**Languages**
English

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by manh21** [comment] 2020-11-07 13:37
Duplicate of #1824

**Closed as completed** 2020-11-07 18:15 UTC
Labels: Duplicate
