### ISSUE TITLE
[<Top Manhua>] Connector not working

### ISSUE THREAD

**Issue by Willbj001** [manga-download/hakuneko#7071] opened 2024-05-08 14:47 UTC
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

The connector is not working for the (Top Manhua) but when on my standard Firefox it works as normal so I looked but the issue is that the there have a new URL it https://manhuatop.org/ for the (Top Manhua)

### To Reproduce

1. Top Manhua 
2. Name of manga The connector not working
3. Name of chapter  The connector not working
4. error pop up message " ERR_NAME_RESOLUTION_FAILED https://topmanhua.com/ "

**Comment by MikeZeDev** [comment] 2024-05-08 17:27
The real issue is that you didnt read the issue template because its says "use nightly build and continue only if the problem is not fixed by nightly". And yet you checked "I used nightly".

https://github.com/manga-download/hakuneko/blob/master/src/web/mjs/connectors/TopManhua.mjs#L10

As you can see, it was fixed a week ago.

**Closed as not planned by MikeZeDev** 2024-05-08 17:27 UTC
Labels: Website Change
