### ISSUE TITLE
[gmanga] Connector not working

### ISSUE THREAD

**Issue by AliFouad1** [manga-download/hakuneko#3473] opened 2021-05-20 01:44 UTC
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**

Yes I did read it

**Is the website of the connector working properly / are you able to see the manga within your browser**

Yes I can open it in my browser

**Describe the bug**

when I click on any manga all chapters named vol.undfiend ch.undfiend and when I download it it instantly fail

**To Reproduce**
1. Name of connector (Gmanga)

**Screenshots**
![Capture](https://user-images.githubusercontent.com/84485465/118906176-eb725800-b925-11eb-8a29-048abc5e31d7.PNG)
please fix it as soon as possible its the best arabic website

**Comment by Robonau** [comment] 2021-05-20 15:49
duplicate of #3426

**Closed as completed** 2021-05-20 16:39 UTC
Labels: Duplicate
