### ISSUE TITLE
[Leitor] Connector not working

### ISSUE THREAD

**Issue by Yxenrox** [manga-download/hakuneko#2350] opened 2020-09-22 20:56 UTC
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes and when you click to open a tab on Hakuneko it loads normally.

**Describe the bug**
It just failed to update the manga list and asks to report.

**To Reproduce**
1. Leitor

![Captura de tela 2020-09-22 175445](https://user-images.githubusercontent.com/13650377/93936613-cb3dbb00-fcfc-11ea-8b02-2c978864befd.png)

**HakuNeko (please complete the following information):**
 - rev 6.1.7

**Comment by XenonR** [comment] 2020-09-27 15:12
Duplicate of #2350

**Closed as completed by XenonR** 2020-09-27 15:12 UTC
Labels: Website Change
