### ISSUE TITLE
[Mangahasu] Connector not working

### ISSUE THREAD

**Issue by TKCeegit** [manga-download/hakuneko#5270] opened 2022-12-22 23:08 UTC
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Does not load any chapters.

**To Reproduce**
1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - 6.1.7

**Comment by MikeZeDev** [comment] 2022-12-23 09:31
Already known: Cant do anything, cloudflare. Duplicate of https://github.com/manga-download/hakuneko/issues/5158

**Closed as not planned by MikeZeDev** 2022-12-23 09:31 UTC
Labels: Duplicate
