### ISSUE TITLE
[kuaikanmanhua] Fix getting paid chapters

### ISSUE THREAD

**Issue by deyvisgt93** [manga-download/hakuneko#5092] opened 2022-10-27 06:19 UTC
Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)
Yes

Is the website of the connector working properly / are you able to see the manga within your browser
Yes

Describe the bug
The last chapters published in kuaikanmanhua.com are not updated in HakuNeko, to avoid errors enter both in my browser and in the internal browser of HakuNeko and in both if the published chapters are seen, but when I put it to download, no update is displayed so I can not download it, and that applies to all series within kuaikanmanhua.com, I hope you can repair this error, I appreciate your attention and work.

To Reproduce

kuaikanmanhua
从大树开始的进化
15, 16

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by MikeZeDev** [comment] 2022-10-27 13:49
Why making a duplicate of https://github.com/manga-download/hakuneko/issues/5086, when you could have just updated the first with the informations ? (Especially the title) ;)

**Closed as not planned** 2022-10-27 20:56 UTC
Labels: Duplicate
