### ISSUE TITLE
[Site Request] Realm Scans

### ISSUE THREAD

**Issue by ghost** [manga-download/hakuneko#4376] opened 2022-02-07 05:21 UTC
**Name of the website**
Realm Scans

**Website urls**
- Site: https://realmscans.com/
- Manga List: https://realmscans.com/series/
- Manga example: https://realmscans.com/series/infinite-level-up-in-murim/
- Chapter online viewer example: https://realmscans.com/infinite-level-up-in-murim-chapter-82/

**Languages**
English

**Comment by manh21** [comment] 2022-02-07 07:42
Duplicate of #4005

**Closed as completed** 2022-02-11 12:05 UTC
Labels: Duplicate
