### ISSUE TITLE
site add mangaphoenix

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#1613] opened 2020-04-30 12:35 UTC
> **From:** 

**Version:** [](https://github.com/manga-download/hakuneko/commits/)

https://mangaphoenix.com/
manga site in Turkish
theme: Wordpress Madara

<details><summary>What has been done?</summary>

</details>

**Comment by XenonR** [comment] 2020-05-02 22:21
@ronny1982 duplicate of #1511

**Closed as completed** 2020-05-02 23:00 UTC
Labels: Duplicate
