### ISSUE TITLE
[TuMangaOnline] Connector not working

### ISSUE THREAD

**Issue by Heavyarms04** [manga-download/hakuneko#4991] opened 2022-09-18 09:31 UTC
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
it is not possible to get a list of chapters, and when it is possible (it rarely does) it is not possible to download the chapters

**To Reproduce**
1. Choose TuMangaOnline connector
4. Connector.mjs:598 Error: Failed to load "https://lectortmo.com/library/manhwa/57333/arcane-sniper" within the given timeout of 60 seconds!
    at Request.mjs:380 
EventTarget {connector: TuMangaOnline, id: "/library/manhwa/57333/arcane-sniper", title: "arcane sniper", status: "completed", chapterCache: Array(0), …}
Manga.mjs:153 _getUpdatedChaptersFromWebsite Error: Failed to load "https://lectortmo.com/library/manhwa/57333/arcane-sniper" within the given timeout of 60 seconds!
    at Request.mjs:380

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

 - Version 6.1.7

I apologize for my terrible command of English, everything was done with google translate

**Comment by MikeZeDev** [comment] 2022-09-18 09:35
Duplicate https://github.com/manga-download/hakuneko/issues/4622

**Comment by Sheepux** [comment] 2022-11-03 21:04
i'll let this one open and renamed the other to have separate issues

**Comment by MikeZeDev** [comment] 2024-06-18 09:18
website changed domain, code changed in the meantime, tested some mangas including this one, cant reproduce.
Closing this issue as too old / probably fixed (timeout are generic)

**Closed as completed by MikeZeDev** 2024-06-18 09:18 UTC
Labels: Website Change
