### ISSUE TITLE
kissmanga site prob

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#1940] opened 2020-06-24 11:37 UTC
> **From:** HakuNeko User

**Version:** [6.1.7@c57aa8](https://github.com/manga-download/hakuneko/commits/c57aa8)

cant download from kissmanga always fail other sites work well but kissmanga is updated at most

<details><summary>What has been done?</summary>

</details>

**Comment by XenonR** [comment] 2020-06-24 12:42
Duplicate of #1938

**Closed as completed by XenonR** 2020-06-24 12:42 UTC
