### ISSUE TITLE
[Muchohentai] Connector not working

### ISSUE THREAD

**Issue by ecchirealm** [manga-download/hakuneko#5093] opened 2022-10-27 21:45 UTC
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes
**Describe the bug**
when trying to download, returns with red exclamation mark

**To Reproduce**
Trying to download any hentai on the website returns with an error, looks like they changed something on the website

**Comment by MikeZeDev** [comment] 2022-10-28 12:25
duplicate of https://github.com/manga-download/hakuneko/issues/3932

**Closed as not planned** 2022-10-28 21:13 UTC
Labels: Duplicate
