### ISSUE TITLE
[Bug] flatpack 

### ISSUE THREAD

**Issue by Ranko-Saotome** [manga-download/hakuneko#6924] opened 2024-03-28 21:01 UTC
os zorin os  17 (ubuntu 22.04)
 flatpak run io.github.hakuneko.HakuNeko
Gtk-Message: 15:57:16.759: Failed to load module "canberra-gtk-module"
Gtk-Message: 15:57:16.760: Failed to load module "canberra-gtk-module"

Usage:
  /app/lib/hakuneko-desktop/hakuneko [OPTIONS]

Options:
  -u, --update-url=<URL>      URL to be checked for web-application updates
                              Default: "http://manga-download.github.io/hakuneko/{version}/latest"
  --startup-url=<URL>         URL to the entrypoint of the web-application
                              Default: "hakuneko://cache/index.html"
  -c, --cache-directory=<DIR> Directory where the web-application is stored
                              Default: system's default
  --user-directory=<DIR>      Directory where user settings are stored
                              Default: system's default

--------------
Framework Info
--------------
Electron : 6.1.7
Chrome   : 76.0.3809.146
Node     : 12.4.0

-------------
Configuration
-------------
Update URL           : https://manga-download.github.io/hakuneko/6.1.7/latest
Connector Protocol   : connector
Application Protocol : hakuneko
Startup URL          : hakuneko://cache/index.html
AppCache Directory   : /home/owner/.var/app/io.github.hakuneko.HakuNeko/cache/hakuneko-desktop
UserData Directory   : /home/owner/.var/app/io.github.hakuneko.HakuNeko/config/hakuneko-desktop

Fontconfig warning: "/etc/fonts/conf.d/05-flatpak-fontpath.conf", line 5: unknown element "reset-dirs"
Fontconfig error: "/etc/fonts/conf.d/05-flatpak-fontpath.conf", line 6: invalid attribute 'salt'
Fontconfig error: "/etc/fonts/conf.d/05-flatpak-fontpath.conf", line 7: invalid attribute 'salt'
Fontconfig warning: "/run/host/font-dirs.xml", line 4: unknown element "remap-dir"
Fontconfig error: "/run/host/font-dirs.xml", line 4: invalid attribute 'as-path'
Fontconfig warning: "/run/host/font-dirs.xml", line 5: unknown element "remap-dir"
Fontconfig error: "/run/host/font-dirs.xml", line 5: invalid attribute 'as-path'
Fontconfig error: Cannot load config file from /run/host/font-dirs.xml
[2:0328/155717.526607:FATAL:gpu_data_manager_impl_private.cc(894)] The display compositor is frequently crashing. Goodbye.
➜  ~

**Comment by Sheepux** [comment] 2024-03-28 21:58
flatpack is not maintained by hakuneko's team

however,, it's probably a duplicate of: https://github.com/manga-download/hakuneko/issues/5792 (try to use --no-sandbox option when runing it from the console)

**Closed as not planned by Sheepux** 2024-03-28 21:58 UTC
Labels: Bug

**Comment by Ranko-Saotome** [comment] 2024-03-28 22:24
Sorry didn't know the flatpak pointed me to this issue page though so I went where it told me to go
