### ISSUE TITLE
[Site Request] Tarot Scans

### ISSUE THREAD

**Issue by Mehmet20032003** [manga-download/hakuneko#6586] opened 2023-12-17 15:02 UTC
**Name of the website**
Tarot Scans

**Website urls (examples below)**
- Site: https://www.tarotscans.com/
- Manga List: https://www.tarotscans.com/az-list/
- Manga example: https://www.tarotscans.com/manga/golden-mage/
- Chapter online viewer example: https://www.tarotscans.com/golden-mage-chapter-37/

**Languages**
Turkish (Türkçe)

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
In Manga List screen we need to click the letters, otherwise only seen the mangas which start with A letter. And there was a Cloudflare problem, but when I entered the website today, Cloudflare screen didn't appear. So can you check it again.

**Comment by MikeZeDev** [comment] 2023-12-17 15:05
PLEASE you made a duplicate of your own issue !!!!
https://github.com/manga-download/hakuneko/issues/5562

**Closed as not planned by MikeZeDev** 2023-12-17 15:05 UTC
Labels: Duplicate
