### ISSUE TITLE
[Sushiscan] Connector not working

### ISSUE THREAD

**Issue by Spit124** [manga-download/hakuneko#5300] opened 2022-12-30 22:39 UTC
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes, but URL changed from https://sushiscan.su/ to https://sushiscan.ru/. New URL (.ru) works properly, former URL (.su) doesn't.

**Describe the bug**
URL changed, from https://sushiscan.su/ to https://sushiscan.ru/

**To Reproduce**
1. Name of connector : Sushi Scans
2. Name of manga (if connector update is working) : no manga available, URL update required
3. Name of chapter (if manga update is working) : no chapter available, URL update required
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12) : N/A

**Screenshots**
N/A

**HakuNeko (please complete the following information):**
 - Version 6.17

**Comment by MikeZeDev** [comment] 2023-01-02 15:27
Duplicate of https://github.com/manga-download/hakuneko/issues/5291

**Closed as not planned** 2023-01-02 15:29 UTC
Labels: Duplicate
