### ISSUE TITLE
[Manga Pro z] Connector not working

### ISSUE THREAD

**Issue by MahmoudRaafatCod** [manga-download/hakuneko#4959] opened 2022-09-06 19:06 UTC
Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)
Yes

Is the website of the connector working properly / are you able to see the manga within your browser
Yes

Describe the bug
The connector url has changed

To Reproduce

Name of connector (Manga Pro z)
Name of manga (if connector update is working) all
Name of chapter (if manga update is working) all
Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)
" Website urls (examples below)

• Site: https://mangaprotm.com/

• Manga List: https://mangaprotm.com/manga/

• Manga example: https://mangaprotm.com/manga/tensei-goblin-dakedo-shitsumon-aru/

• Chapter online viewer example: https://mangaprotm.com/dfg654df654gdf/
"

HakuNeko (please complete the following information):

Version [e.g. 6.17]

**Comment by MikeZeDev** [comment] 2022-09-11 13:07
Duplicate of https://github.com/manga-download/hakuneko/issues/4959. Please do not reopen issue for the same error and website, it wont speed up the process.

**Comment by Sheepux** [comment] 2022-09-12 17:54
duplicate #4934

**Closed as not planned by Sheepux** 2022-09-12 17:54 UTC
Labels: Duplicate
