### ISSUE TITLE
[MangaKawaii] Connector not working

### ISSUE THREAD

**Issue by didierGuieu** [manga-download/hakuneko#5530] opened 2023-03-04 08:27 UTC
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Error when downloading a chapter
Connector.mjs:618 TypeError: Cannot read property '1' of null
    at MangaKawaii._getPages (MangaKawaii.mjs:63)
    at async MangaKawaii._getPageList (Connector.mjs:615) EventTarget

**To Reproduce**
1. MangaKawaii
3. MartialPeak
4. 3106 (example)
5. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)
Connector.mjs:618 TypeError: Cannot read property '1' of null
    at MangaKawaii._getPages (MangaKawaii.mjs:63)
    at async MangaKawaii._getPageList (Connector.mjs:615) EventTarget

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]. Latest

**Comment by MikeZeDev** [comment] 2023-03-04 10:49
Cant reproduce . Make sure to use nightly version as something was fixed in January for this website.

**Closed as not planned** 2023-03-04 10:52 UTC
Labels: Can't reproduce bug

**Comment by didierGuieu** [comment] 2023-03-04 11:32
Thanks, it works with the nightly version
