### ISSUE TITLE
[Site Request] Mangaowl

### ISSUE THREAD

**Issue by shriza02** [manga-download/hakuneko#4385] opened 2022-02-09 13:15 UTC
**Name of the website**
Mangaowl

**Website urls**
- Site: https://mangaowls.com/
- Manga List: https://mangaowls.com/genres/shounen-ai
- Manga example: https://mangaowls.com/single/55550/heaven-official-s-blessing
- Chapter online viewer example: https://i.mangaowls.com/reader/55550/1539164/0?tr=QQ%2FNEplf63%2BMz5K3asXEnw%3D%3D&s=aHR0cHM6Ly9tYW5nYW93bHMuY29t

**Languages**
English

**Comment by manh21** [comment] 2022-02-10 07:25
Duplicate of https://github.com/manga-download/hakuneko/issues/2335

**Closed as completed** 2022-02-11 12:01 UTC
Labels: Duplicate
