### ISSUE TITLE
[swatmanga.me] Connector not working

### ISSUE THREAD

**Issue by TheRebel03** [manga-download/hakuneko#5166] opened 2022-11-19 13:07 UTC
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
The connector URL has changed.

**To Reproduce**
1. Name of connector: swat manga
2. Name of manga (if connector update is working)-All
3. Name of chapter (if manga update is working)-All
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

Website new URLs

Site: https://swatmanga.me/
Manga List: https://swatmanga.me/manga/
Manga example: https://swatmanga.me/manga/make-the-level-up-to-max/
Chapter online viewer example: https://swatmanga.me/751855/make-the-level-up-to-max-1/
HakuNeko (please complete the following information):

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by MikeZeDev** [comment] 2022-11-19 16:32
Duplicate of https://github.com/manga-download/hakuneko/issues/4983

**Closed as not planned** 2022-11-19 21:03 UTC
Labels: Duplicate
