### ISSUE TITLE
[Site Request] MangaOwl

### ISSUE THREAD

**Issue by dmmfs** [manga-download/hakuneko#4350] opened 2022-01-26 15:24 UTC
**Name of the website**
MangaOwl

**Website urls (examples below)**
- Site: https://mangaowl.net
- Manga List: 
- Manga example: https://mangaowl.net/single/65049/ring-my-bell
- Chapter online viewer example: 

**Languages**
List of languages supported by the website
English, Japanese

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by manh21** [comment] 2022-01-26 15:39
Duplicate of #2335

**Closed as completed** 2022-01-27 07:42 UTC
Labels: Duplicate
