### ISSUE TITLE
[hitomi.la] Connector not working

### ISSUE THREAD

**Issue by DarkBlooDStone** [manga-download/hakuneko#4522] opened 2022-03-29 01:26 UTC
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
No

**Describe the bug**

No url address of this site is recognized 

**To Reproduce**
1. Name of connector hitomi.la
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

![Sin título](https://user-images.githubusercontent.com/53885246/160513872-9e4355d2-0b90-471c-ba64-90b742935a9c.jpg)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by MikeZeDev** [comment] 2022-10-04 13:25
duplicate of https://github.com/manga-download/hakuneko/issues/4356

@Sheepux pls <3

**Closed as not planned** 2022-10-04 14:53 UTC
Labels: Duplicate
