### ISSUE TITLE
[NameOfConnector] Connector not working

### ISSUE THREAD

**Issue by dengole899** [manga-download/hakuneko#4348] opened 2022-01-25 23:25 UTC
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**

**To Reproduce**
1. Doujindesi
2. website change to doujindesu.xxx

**Screenshots**
![image](https://user-images.githubusercontent.com/83463674/151076444-cd32acf6-71e5-47b2-a484-191b517090c1.png)
![image](https://user-images.githubusercontent.com/83463674/151076700-283f4f69-7795-4b3d-9735-2f5d55406256.png)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by manh21** [comment] 2022-01-26 04:32
Duplicate of #4272 and alreadey fixed on #4325

**Closed as completed** 2022-01-27 07:59 UTC
Labels: Duplicate
