### ISSUE TITLE
japanread.cc Connector not working

### ISSUE THREAD

**Issue by wakhyz** [manga-download/hakuneko#5029] opened 2022-10-01 19:09 UTC
i apologize, i'm a french newbie.

**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
it's a cloudflare issue.

**To Reproduce**
1. japanread.cc
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Failed to load resource: the server responded with a status of 403 ()

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by MikeZeDev** [comment] 2022-10-04 08:48
Duplicate of https://github.com/manga-download/hakuneko/issues/4513

**Closed as not planned** 2022-10-22 20:49 UTC
Labels: Duplicate
