### ISSUE TITLE
[bato.to] Connector not working

### ISSUE THREAD

**Issue by fatezuru** [manga-download/hakuneko#4631] opened 2022-04-30 06:08 UTC
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

The connector won't update and can't download chapters. Whenever I click a title, it will just notify that it is offline and is only accessible in the manga directory. Copying and pasting the link is not working too.

**Comment by MikeZeDev** [comment] 2022-05-05 18:28
Duplicate of https://github.com/manga-download/hakuneko/issues/4632

**Closed as completed** 2022-05-16 06:10 UTC
Labels: Website Change
