### ISSUE TITLE
[Site Request] MangaBuddy

### ISSUE THREAD

**Issue by Nevarneyokbigorelim** [manga-download/hakuneko#5107] opened 2022-11-01 17:14 UTC
**Name of the website**
MangaBuddy

**Website urls (examples below)**
- Site: https://mangabuddy.com
- Manga List: https://mangabuddy.com/manga-list
- Manga example: https://mangabuddy.com/gu-hos-escape
- Chapter online viewer example: https://mangabuddy.com/gu-hos-escape/chapter-1

**Languages**
English

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").
https://mangamirror.com
**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment] 2022-11-01 21:45
Duplicate of https://github.com/manga-download/hakuneko/issues/4346

**Closed as not planned** 2022-11-03 21:06 UTC
Labels: Duplicate
