### ISSUE TITLE
[KissComic/ReadcomicOnline] Connector not working

### ISSUE THREAD

**Issue by deltz025** [manga-download/hakuneko#5253] opened 2022-12-18 16:58 UTC
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
The ReadComicOnline connector fails to load the manga/comic list. The network monitor reports an immediate 503 error. 

**To Reproduce**
1. Select the KissComic connector. 
2. Click on the icon to refresh the list. 
3. The icon will spin briefly (the first time) or not at all (subsequent attempts). No list will be loaded. 

**Screenshots**
![image](https://user-images.githubusercontent.com/49649081/208310071-f4018aaf-5453-44fc-8835-d2c3b652df86.png)

**HakuNeko (please complete the following information):**
 - Version 6.17@a8da6a

**Comment by MikeZeDev** [comment] 2022-12-18 17:24
Cant reproduce on nightly.

**Comment by MikeZeDev** [comment] 2022-12-19 10:38
There was a fix for this website last month but it was for getting pages. And its not yet available on realease version.
You may want to give nightly build a try, who knows?

**Comment by MikeZeDev** [comment] 2023-01-19 17:41
Website is having hiccups sometimes, confirmed yesterday. Nothing to do.

**Closed as not planned by MikeZeDev** 2023-01-19 17:41 UTC
Labels: Can't reproduce bug
