### ISSUE TITLE
[Site Request] MangaReader.to

### ISSUE THREAD

**Issue by Weebster69** [manga-download/hakuneko#4332] opened 2022-01-23 10:21 UTC
**Name of the website**
MangaReader

**Website urls (examples below)**
- Site: https://mangareader.to/
- Manga List: https://mangareader.to/type/manga
https://mangareader.to/type/manhwa
https://mangareader.to/type/manhua
 
- Manga example: https://mangareader.to/boruto-naruto-next-generation-8419
- Chapter online viewer example: https://mangareader.to/read/boruto-naruto-next-generation-8419/en/chapter-66

**Languages**
List of languages supported by the website : English, Japanese, Korean, Chinese

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by manh21** [comment] 2022-01-23 11:21
Duplicate of #3979

**Closed as completed** 2022-01-23 15:19 UTC
Labels: Duplicate
