### ISSUE TITLE
[NameOfConnector] Connector not working

### ISSUE THREAD

**Issue by ghost** [manga-download/hakuneko#5194] opened 2022-11-30 18:10 UTC
When I try to download manga from lezhin, I get a download failed error:
![image](https://user-images.githubusercontent.com/79840490/204875347-43c29768-5bd6-4bca-bd20-a1964ea4c636.png)

Also, when I try to open it in preview, I get this error:
![Ekran görüntüsü 2022-11-30 210809](https://user-images.githubusercontent.com/79840490/204875133-eca69be2-17a2-413e-b6e0-5f117b67a5cf.png)

I logged into my lezhin account from settings (korean).

**Comment by MikeZeDev** [comment] 2022-11-30 19:30
Duplicate of https://github.com/manga-download/hakuneko/issues/5044

**Closed as not planned** 2022-12-01 12:44 UTC
Labels: Duplicate
