### ISSUE TITLE
9anime Connector not working

### ISSUE THREAD

**Issue by shashankx86** [manga-download/hakuneko#5297] opened 2022-12-30 17:12 UTC
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
No

**Describe the bug**
unable to connect to 9anime.to

**To Reproduce**
1. 9anime
2. n
3. n
4. failed to connect to 9anime 60 second timeout

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by MikeZeDev** [comment] 2022-12-30 17:51
Duplicate of https://github.com/manga-download/hakuneko/issues/4561

**Closed as not planned by MikeZeDev** 2022-12-30 17:51 UTC
Labels: Duplicate
