### ISSUE TITLE
[Bug] Download/View doesn't work with JapScan

### ISSUE THREAD

**Issue by Shd-matsuyo** [manga-download/hakuneko#5208] opened 2022-12-07 09:25 UTC
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Describe the bug**
Unable to download or view any scan from JapScan [FR]
that directly fails

**To Reproduce**

**Expected behavior**
That downloads and viewing are possible as before

**Screenshots**

**Context (please complete the following information):**
 - OS: W10 22H2
 - HakuNeko Version 6.1.7

**Additional context**
Nope

**Comment by MikeZeDev** [comment] 2022-12-07 10:05
Duplicate of https://github.com/manga-download/hakuneko/issues/4657

**Closed as not planned by MikeZeDev** 2022-12-07 10:05 UTC
Labels: Duplicate
