### ISSUE TITLE
[Site Request] Getcomics

### ISSUE THREAD

**Issue by vdanu** [manga-download/hakuneko#5187] opened 2022-11-29 01:40 UTC
**Name of the website**
Getcomics

**Website urls (examples below)**
- Site: https://getcomics.info
- Manga List: https://getcomics.info/tag/indie-week/
- Manga example: https://getcomics.info/marvel/the-amazing-spider-man-14-2022/
- Chapter online viewer example: https://thewebsiteurl/manga/0012/view.html

**Languages**
English

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment] 2022-11-29 09:53
Duplicate of https://github.com/manga-download/hakuneko/issues/4641. Also, you may want to read what i wrote in the mentioned issue. I wonder what to do.

**Closed** 2022-12-01 17:17 UTC
Labels: Website Suggestion
