### ISSUE TITLE
[NameOfConnector] Connector not working

### ISSUE THREAD

**Issue by Harsh-701** [manga-download/hakuneko#3479] opened 2021-05-21 09:07 UTC
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
No

**Describe the bug**
Failed to update the list of MangaPark
Failed to receive content from "https://v3.mangapark.net/ajax.reader.home.release" (status:405)-
No changes in settings were made whatsoever before getting this error. In fact, after downloading the software, I mentioned the name of above website first as it was the main reason for downloading this software in the first place. No issue in internet connection as I even tried different sites into connector and they worked. Same issue with the same website in different manga downloader as well and that led me here. 

**To Reproduce**
1. MangaPark
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Failed to update the list of MangaPark
Failed to receive content from "https://v3.mangapark.net/ajax.reader.home.release" (status:405)-

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by dodieboy** [comment] 2021-05-21 10:12
Duplicate of #3433

**Closed as completed** 2021-05-21 13:49 UTC
Labels: Duplicate
