### ISSUE TITLE
Website Change Japscan.ws to Japscan.me

### ISSUE THREAD

**Issue by drl77** [manga-download/hakuneko#5104] opened 2022-11-01 13:05 UTC
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes/No

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes/No

**Describe the bug**

**To Reproduce**
1. Name of connector : Japscan.ws
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Website Change Japscan.ws to Japscan.me

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by MikeZeDev** [comment] 2022-11-01 16:05
No need for two issues :)
 Duplicate of https://github.com/manga-download/hakuneko/issues/5105

**Closed as not planned** 2022-11-02 16:45 UTC
Labels: Duplicate
