### ISSUE TITLE
Bacamanga

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#2163] opened 2020-08-12 03:29 UTC
> **From:** HakuNeko User

**Version:** [6.1.7@8f3184](https://github.com/manga-download/hakuneko/commits/8f3184)

Tidak bisa update list dari bacamanga

<details><summary>What has been done?</summary>

☑ Searched for Similar Issues: https://git.io/hakuneko-issuesearch

</details>

**Comment by Sheepux** [comment] 2020-08-12 09:17
Support is provided in english.
Tested bacamanga. Works fine.
Solve the captcha prompted or use manual website interraction.

Not much details + Not able to reproduce --> Closing
Feel free to give more details and ask to reopen the ticket.

**Closed as completed by Sheepux** 2020-08-12 09:17 UTC
Labels: Invalid, Website Change
