### ISSUE TITLE
[Batoto] Connector not working

### ISSUE THREAD

**Issue by eminanmm** [manga-download/hakuneko#4640] opened 2022-05-03 13:22 UTC
Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)
Yes

Is the website of the connector working properly / are you able to see the manga within your browser
Yes

Describe the bug
Manga/chapter does not load at the query and sometimes there's always an "CryptoJS is not defined" error in downloading chapters in Batoto

1. Name of connector is Batoto
2. Affected any manga at Batoto
3. Manga/Chapter is not displayed at the query. (Reproducibility: High)
4. Sometimes when the manga/chapter loads there's an error display and the download does not proceed.
5.  Here's the screenshot for the error in the console.

Screenshots
![image](https://user-images.githubusercontent.com/104840276/166460405-5e42c7a1-7f5c-47d4-806e-db8fc9c902d4.png)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by MikeZeDev** [comment] 2022-05-05 18:29
duplicate of https://github.com/manga-download/hakuneko/issues/4632
 https://github.com/manga-download/hakuneko/issues/4631

**Comment by MikeZeDev** [comment] 2022-05-05 18:32
Cant reproduce on nightly. Any manga to try in particular?

**Closed as completed** 2022-05-05 19:09 UTC
Labels: Duplicate

**Comment by eminanmm** [comment] 2022-05-06 02:38
I was able to reproduce this by downloading at least 20 manga or 20 plus chapters.
Here are the list of manga you can use for reproducing the bug.





[tobeTest.txt](https://github.com/manga-download/hakuneko/files/8637195/tobeTest.txt)

**Comment by MikeZeDev** [comment] 2022-05-06 09:45
Tried 3 random links from your list. Everything works as intended. Download is quite fast .

https://i.imgur.com/yGkd89H.png https://i.imgur.com/JRSsFle.png https://i.imgur.com/p128r2d.png

If you are not using nightly version, you may give it a try. Nothing to see :/

**Comment by eminanmm** [comment] 2022-05-06 12:54
I tried the nighty version 8.3.4 portable.
this is the error its giving. I don't know why the error keeps happening on my end even I have acceptable internet speed.
![image](https://user-images.githubusercontent.com/104840276/167135250-5748aec0-e165-4ab7-9e52-b4df0b2b4e46.png)

**Comment by Sheepux** [comment] 2022-05-06 13:07
does https://bato.to/series/75571/promise-cinderella works in your normal browser at least ?
It works fine here in mine & in hakuneko

**Comment by eminanmm** [comment] 2022-05-06 13:10
Yes it works on the browser, sometimes hakuneko was able to get the manga but after queuing another set of manga it was not able to get its data.

**Comment by Sheepux** [comment] 2022-05-06 13:12
then it's probably a throttling protection mechanism that we're not aware (there's no throttling in the batoto connector currently)
It probably won't be fixed as we're fully working on haruneko (unless some other kind souls sees this)

**Comment by eminanmm** [comment] 2022-05-06 13:15
Oh, I see. Thank you for accommodating my issue. I hope someday or someone will be able to fix this. Thank you. :)
