### ISSUE TITLE
[9anime] Connector not working

### ISSUE THREAD

**Issue by XanderThunder** [manga-download/hakuneko#2419] opened 2020-10-10 13:31 UTC
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
When synchronizing the local database with cloud an error message pops up saying "Failed to update manga list for 9ANIME\nCannot read property 'textContent' of undefined". This happens every time you click on it. I tried a serverreboot, connecting to a VPN in America and also looked at the Firewall blocks. It seems as though the problems lies within HakuNeko. 

**To Reproduce**
1. Open HakuNeko Desktop
2. Click on the green synchronize button in the top left next to connector
3. Now an errormessage should pop up

**Screenshots**
<img width="1255" alt="9anime not wroking" src="https://user-images.githubusercontent.com/57769828/95656249-572d5080-0b0d-11eb-8bc7-cb27b7ff7bdb.png">

**HakuNeko**
 - Version 6.1.7 (Stable)

**Comment by newaccforhc** [comment] 2020-10-11 04:33
Duplicate of #2393
Pls search the issues before creating new one..
Closing this...

**Closed as completed** 2020-10-11 04:34 UTC
Labels: Duplicate
