### ISSUE TITLE
[Site Request] bufftoon

### ISSUE THREAD

**Issue by rhkrehdnjs** [manga-download/hakuneko#2613] opened 2020-11-09 04:45 UTC
**Name of the website**
bufftoon

**Website urls (examples below)**
- Site: https://bufftoon.plaync.com/
- Manga List: https://bufftoon.plaync.com/webtoon/scheduled?days=0
- Manga example: https://bufftoon.plaync.com/series/773433/3006777
- Chapter online viewer example: https://bufftoon.plaync.com/series/773433/3006777

**Languages**
List of languages supported by the website

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by manh21** [comment] 2020-11-09 04:47
Duplicate of #2111

**Closed as completed** 2020-11-09 12:46 UTC
Labels: Duplicate
