### ISSUE TITLE
[Site Request] コミックシーモア (Comic Seymour)

### ISSUE THREAD

**Issue by hipposofdeath** [manga-download/hakuneko#2748] opened 2020-12-13 01:20 UTC
**Name of the website**
コミックシーモア (Comic Seymour)

**Website urls (examples below)**
- Site: https://www.cmoa.jp/
- Manga List (this is just the top manga list): https://www.cmoa.jp/genre/top/
- Manga example: https://www.cmoa.jp/title/55518/
- Chapter online viewer example: https://www.cmoa.jp/bib/speedreader/speed.html?cid=0000055518_jp_0001&u0=0&u1=0&rurl=https%3A%2F%2Fwww.cmoa.jp%2Fmypage%2Fmypage_top%2F%3Ftitle%3D55518

**Languages**
Japanese

**Website relationship*
It looks like ebookjapan, or any other Japanese ebook website. 

**Additional details**
It uses an online in-website reader.

**Comment by manh21** [comment] 2020-12-13 01:25
Duplicate of #2307

**Closed as completed** 2020-12-14 08:48 UTC
Labels: Duplicate
