### ISSUE TITLE
[Site Request] novelcool [Webtoon,Manga,Novel]

### ISSUE THREAD

**Issue by areglos** [manga-download/hakuneko#1769] opened 2020-05-24 10:04 UTC
It's a little complicated site. Combined with the novel.  

Lg; https://   "  Country   "   .novelcool.com  " It supports a few more languages."  "BR,RU, İT and...

Manga/Webtoon examples
Site; https://www.novelcool.com/
Webtoon Link; https://www.novelcool.com/novel/Starting-From-Today-I-ll-Work-As-A-City-Lord.html
Read Webtoon; https://www.novelcool.com/chapter/Ch-0/4058817/
Read Page 1; https://www.novelcool.com/chapter/Ch-0/4058817-1.html
Read Page 2; https://www.novelcool.com/chapter/Ch-0/4058817-2.html

Manga/Webtoon/Manhua/Manhwa/WebComic List; 

Manga List; https://www.novelcool.com/category/Manga.html
Webtoon List; https://www.novelcool.com/category/Webtoon.html
Webtoons 2 List; https://www.novelcool.com/category/Webtoons.html
Manhua; https://www.novelcool.com/category/Manhua.html
Manhwa; https://www.novelcool.com/category/Manhwa.html
Web Comic; https://www.novelcool.com/category/Web+comic.html

Light Novel examples(TEXT PAGE);
Site; Site; https://www.novelcool.com/
**Read List; https://www.novelcool.com/category.html**
LightNovel; https://www.novelcool.com/novel/the-divine-physicians-overbearing-wife.html
LighNovel Read ; https://www.novelcool.com/chapter/The-Divine-Physician-s-Overbearing-Wife-State-Preceptor-Your-Wife-Has-Fled-Again-The-Divine-Physician-s-Overbearing-Wife-State-Preceptor-Your-Wife-Has-Fled-Again-Chapter-1-/4031806/
LighNovel Read 2 ; https://www.novelcool.com/chapter/The-Divine-Physician-s-Overbearing-Wife-State-Preceptor-Your-Wife-Has-Fled-Again-Chapter-2/4031807/

**Comment by dodieboy** [comment] 2020-06-14 06:37
@ronny1982 Duplicate of #528

**Closed as completed** 2020-06-16 21:23 UTC
Labels: Duplicate
