### ISSUE TITLE
Can't get manga from MangaKakalot sites

### ISSUE THREAD

**Issue by Iloveboobs84** [manga-download/hakuneko#922] opened 2020-01-12 22:21 UTC
I tried again after the Nightly version download and Manga are still missing chapters from these sites 
[MangaDex] and [MangaKakkalot]

Missing Manga list 
1) Boku no Kanojo Sensei
2) Fairy Tail 100yr quest
3) Freezing
4) Goblin Slayer Year One
5) Go Touban (aka 5 Sister manga)
6) Kenja no Mango
7) Maou Gakuin no Futekigousha
8) Nanatsu no Taizai
9) Tate no Yuusha no Narigari

I'm sure there are more missing but these are the ones I was looking for.

If there not missing chapters than my Windows 10 is not letting it updates and How would I fix it to update.

**Comment by ronny1982** [comment] 2020-01-12 22:58
Have you tested if these are fully available on the website?
HakuNeko only shows what is available on the website.

**Comment by dodieboy** [comment] 2020-01-13 01:37
Tested, these are fully available on the website
![image](https://user-images.githubusercontent.com/9015764/72229276-46849400-35e8-11ea-9d0b-ed1d12ff60e0.png)
![image](https://user-images.githubusercontent.com/9015764/72229282-5308ec80-35e8-11ea-8dfa-e62eda821e8d.png)

**Comment by Iloveboobs84** [comment] 2020-01-13 03:07
I test all manga websites to see if the Chapters are AVAILABLE before trying to download them from HakunNeko. Currently On Websites but Unavailable in the download programs with ZERO Chapters.

**Comment by Iloveboobs84** [comment] 2020-01-13 03:54
As of right NOW, I checked for the 2nd time today and these are the Updates for mangadex from the list not shown in Hakuneko Desktop

Also, mangadex changed from .com to .cc might be the reason it's not working. Doman needs to be updated in the Downloaders Code. 

Boku no Kanojo Sensei - updated to Ch 09
Fairy Tail 100yr quest - updated to Ch 45
Freezing - updated to Ch 225
5Touban no Hanayome - updated to Ch 116
Kenja no Mango - updated to Ch 36
Maou Gakuin no Futekigousha - updated to Ch 13.2
Nanatsu no Taizai - updated to Ch 335
Tate no Yuusha no Nariagari {aka Shield Hero} - updated to Ch 61

Also No listing for Fairy Tail Happy's Great Adventure Side story to manga list

Goblin Slayer Year One is - updated to Ch 34 on Manganelo.com previously Mangakakalot

**Comment by ronny1982** [comment] 2020-01-13 06:41
For MangaDex See #885

**Comment by Iloveboobs84** [comment] 2020-01-13 17:05
> For MangaDex See #885

Why? do you keep referring to that it's NOT fixing the Missing Chapter Issue. I have the Latest UPDATE aka Nightly Build. List from above is What the issue is. There ARE Missing Chapters NOT available in Hakuneko that are CLEARLY on the webpages. By clicking the Reload/Update Button only refreshes the list and DON'T update. The issue is NOT resolved yet. Please look into it and fix it ASAP. I'm not the only one who has pointed it out. **dodieboy** did too by the picture above and you can clearly see there are NO chapters next to the Manga Goblin Slayer Year One's name.

**Comment by ronny1982** [comment] 2020-01-13 18:10
HakuNeko can only download chapters that are available on their website.
As mentioned on MangaDex forum, there are still missing chapters through migration.
If you find a chapter that is available on their website but not in HakuNeko, please provide manga and chapter name, the developers cannot go randomly through 35000 mangas and check for missing chapters.

**Comment by ronny1982** [comment] 2020-01-13 18:18
> Tested, these are fully available on the website but not on HakuNeko

Issue cannot be reproduced from my end  with **MangaKakalot** and **Goblin Slayer**.
In your screenshot the manga is not selected, you need to select a manga to show its chapters.
Furthermore have you tried the nightly build?

<img width="1232" alt="Screen Shot 2020-01-13 at 7 14 35 PM" src="https://user-images.githubusercontent.com/27136773/72280658-1d402400-3639-11ea-9252-1615b2487ca6.png">

**Comment by ronny1982** [comment] 2020-01-13 18:40
From my end with ngihtly build:
<img width="1232" alt="Screen Shot 2020-01-13 at 7 37 54 PM" src="https://user-images.githubusercontent.com/27136773/72282188-68a80180-363c-11ea-81db-52e7c5ef1782.png">

MangaDex website:
<img width="968" alt="Screen Shot 2020-01-13 at 7 38 40 PM" src="https://user-images.githubusercontent.com/27136773/72282200-6f367900-363c-11ea-9c56-3e7bbb6e4d1e.png">

**Comment by Iloveboobs84** [comment] 2020-01-13 19:39
> From my end with ngihtly build:
> 
> MangaDex website:

Excuse me are u blind. The screenshot is not Mine and in your screenshot, you selected Goblin Slayer, not Goblin Slayer YEAR ONE which is reported along with the rest not INCLUDING Boku no Kanojo Sensei. Yes, I am on the Nightly Version.

**Comment by ronny1982** [comment] 2020-01-13 21:11
> **dodieboy** did too by the picture above and you can clearly see there are NO chapters next to the Manga Goblin Slayer Year One's name.

Sorry for the misunderstanding, but your reply precisely says that there are no chapters in the screenshot. Also there is not even a manga `Goblin Slayer Year One` in the list. `One Piece` is also not in the list, does it mean that there are no chapters for `One Piece`? No because it is not in the list and therefore not selected. I just stated that fact: no selected manga => no chapters in the chapter list.

However, since i cannot reproduce the issue on my end and it also seems i'm not qualified enough to handle the customer support for this case in a constructive manner, i will leave it to one of the other developers / community members.

**Comment by Sheepux** [comment] 2020-01-13 22:06
Just checked, there is no issue with MangaDex if you're using the nightly (i can see all mentionned chapters)

As for MangaKakkalot, it's an issue with the website hotlinking to MangaNelo. You should check directly the MangaNelo website.
Roony fixed such cas with a user warning: https://github.com/manga-download/hakuneko/pull/924

/suggest-closing unless further issue

**Comment by dodieboy** [comment] 2020-01-14 03:26
Just checked, the issue is fixed
![image](https://user-images.githubusercontent.com/9015764/72311745-a8b0c800-36c0-11ea-99db-98ebaa870355.png)

**Comment by ronny1982** [comment] 2020-01-16 21:06
I guess this is solved for now.
If any related errors occurs, please open a new ticket.

**Closed by ronny1982** 2020-01-16 21:06 UTC
