### ISSUE TITLE
[1st Kiss Manga] Connector not working

### ISSUE THREAD

**Issue by samanta-widjaja** [manga-download/hakuneko#5623] opened 2023-03-29 02:19 UTC
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Did you [try Nightly Build](https://github.com/manga-download/hakuneko/releases) ?**
No

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes
**Describe the bug**
Cannot update manga list. Although already updated

Request URL: https://1stkissmanga.me/wp-admin/admin-ajax.php
Request Method: POST
Status Code: 403 
Remote Address: 104.18.3.8:443
Referrer Policy: no-referrer-when-downgrade

**To Reproduce**
1. 1st Kiss Manga
2. update manga list not working. show 0 list
3. Request URL: https://1stkissmanga.me/wp-admin/admin-ajax.php
Request Method: POST
Status Code: 403 
Remote Address: 104.18.3.8:443
Referrer Policy: no-referrer-when-downgrade

**HakuNeko (please complete the following information):**
 - Version [6.17]

**Comment by MikeZeDev** [comment] 2023-03-29 08:26
Cant reproduce. Try nightly maybe?

**Comment by samanta-widjaja** [comment] 2023-03-29 09:01
when i first view from hakuneko internal web browser, it fine. But after I update manga list, through hakuneko web, it shows your browser is out of date. i use the portable version. help please?

**Comment by MikeZeDev** [comment] 2023-03-29 11:46
Out of date? That would be the sign of Cloudflare, but i see no sign of Cloudflare blocking, or i should have been affected too.

I tell you, use nightly (portable or not we dont care) maybe it will work.

**Comment by MikeZeDev** [comment] 2023-03-29 11:51
After browsing a bit and after seeing some manga chapter properly, Cloudflare comes, cant fix

Edit :  working again after closing hakuneko. Better NOT using internal browser then.

**Closed as completed** 2023-04-12 18:37 UTC
Labels: Cloudflare/Geoblocking
