### ISSUE TITLE
[Mangakatana] only one page downloads

### ISSUE THREAD

**Issue by stevkats** [manga-download/hakuneko#5064] opened 2022-10-14 16:08 UTC
Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)
**Yes**

Is the website of the connector working properly / are you able to see the manga within your browser
**Yes**

Describe the bug
When downloading chapters in .cbz format from any manga in bookmarks, downloaded archive contains only ONE page. Website is working fine, can view/read all pages.

To Reproduce

1. Mangakatana
2. Any manga (if connector update is working)
3. Any chapter (if manga update is working)

HakuNeko: Version 6.17

Attached:
1) Developer Console Network tab screenshot (example here is download of Jujutsu Kaizen Chapter 201)
![image](https://user-images.githubusercontent.com/22016819/195890639-e445c484-3e8a-4a12-b922-b9ef5c435e7b.png)
2) TXT version files of 2 HAR files in above screenshot (hope they help)
[cache (payload).txt](https://github.com/manga-download/hakuneko/files/9788055/cache.payload.txt)
[cache (0.jpg).txt](https://github.com/manga-download/hakuneko/files/9788056/cache.0.jpg.txt)

**Comment by MikeZeDev** [comment] 2022-10-15 10:31
This has been fixed already by this https://github.com/manga-download/hakuneko/pull/5020. Use nightly version or wait for the fixes to land in main branch.

Duplicate of : https://github.com/manga-download/hakuneko/issues/4987

**Closed as not planned** 2022-10-15 18:49 UTC
Labels: Duplicate
