### ISSUE TITLE
[Bug] Can't Enjoy the Downloaded File

### ISSUE THREAD

**Issue by MonsieugarDaddy** [manga-download/hakuneko#4726] opened 2022-06-06 12:22 UTC
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Describe the bug**
I cannot seem to download the picture.. well, I can download it, but the file is just broken. When I downloaded a certain chapter (i.e.: Black Clover 331), the output only showed files with **_.bin_** extension instead of **_.jpg_**, **_.jpeg_**, or **_.png_**; the issue occurs on MangaTown & MangaHere, I dunno if the same case exists elsewhere.

**To Reproduce**
1. Select a website (MangaTown or MangaHere)
2. Select any manga & any chapter to download
3. Open your folder of downloaded chapter
4. Witness the majestic bugs 👀

**Expected behavior**
an outcome of solid pictures just like what the usual HakuNeko offers ):

**Screenshots**
![HaquNeqo](https://user-images.githubusercontent.com/55888814/172158932-3d338462-6a29-43b8-a0b8-5bd60b037983.png)

**Context (please complete the following information):**
 - OS: Windows 11 Pro
 - 6.17

**Additional context**
I'm from **Indonesia** & I can access the site just fine, even without a VPN.
I tried downloading 1 random chapter from **Kissmanga & it works just fine**.

**Comment by Sheepux** [comment] 2022-06-12 11:42
bin files are usually related to bad internet connexion and/or website not sending adequate headers on image.
Can you try to rename the images to jpeg and see if they work fine or are corrupted ?

**Comment by MonsieugarDaddy** [comment] 2022-06-19 07:32
I doubt that a bad internet connection is an issue here since I was able to download 1 random chapter from another Kissmanga. Renaming the file _doesn't really help_ either.. when the .bin file itself is only worth **20KB** at its largest (while the normal manga images are worth around **120-500KB**)

thanks for the reply though!

**Comment by MikeZeDev** [comment] 2022-11-09 19:40
Mangahere works.

Mangatown is still downloading bin. The problem is : they use Mangahere CDN. The bin file downloaded are actually html files.

In order to download files from Mangahere CDN in this connector we shall send mangahere.com as referer. Then, it works !

**Comment by MikeZeDev** [comment] 2022-11-09 20:56
Fixed by https://github.com/manga-download/hakuneko/pull/5133

**Closed as completed** 2022-12-04 12:12 UTC
Labels: Bug
