### ISSUE TITLE
[line webtoons ] Connector not working properly 

### ISSUE THREAD

**Issue by Robonau** [manga-download/hakuneko#1861] opened 2020-06-08 04:29 UTC
**Did you read [the troubleshooting guide](https://github.com/manga-download/hakuneko/wiki/Troubleshooting)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
it only shows the 10 most resent chapters of "the gamer" possibly others
probably dew to how webtoons.com only has 10 an any given page but not sure

**To Reproduce**
1. www.webtoons.com
2. "the gamer"

**Screenshots**
https://imgur.com/a/3jWJXCG
it has all the chapters on the site but only 10 show up in hakuneko

 - Version [e.g. 6.17]

**Comment by dodieboy** [comment] 2020-06-14 06:21
@ronny1982 Duplicate of #1635 

This error is fixed already, please try using the latest nightly build

**Closed as completed** 2020-06-16 20:46 UTC
Labels: Website Change
