### ISSUE TITLE
[Site Request] Suryascansesp

### ISSUE THREAD

**Issue by Lenoyr** [manga-download/hakuneko#5018] opened 2022-09-27 22:02 UTC
**Name of the website**
Suryascansesp

**Website urls (examples below)**
- Site: https://apolomanga.com/
- Manga List: https://apolomanga.com/directorio/
- Manga example: https://apolomanga.com/ver/1
- Chapter online viewer example: https://apolomanga.com/ver/1/30

**Languages**
Spanish

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment] 2022-12-01 19:26
Duplicate of https://github.com/manga-download/hakuneko/issues/5017 (same url)

**Closed as not planned by MikeZeDev** 2022-12-01 19:26 UTC
Labels: Duplicate
