### ISSUE TITLE
[Site Request arabic] 

### ISSUE THREAD

**Issue by nottyd** [manga-download/hakuneko#2539] opened 2020-10-29 04:31 UTC
**Name of the website**
mangaproz

**Website urls (examples below)**
- Site: https://mangaproz.com/
- Manga List: https://mangaproz.com/manga/
- Manga example: https://mangaproz.com/manga/freaking-romance/
- Chapter online viewer example: https://mangaproz.com/freaking-romance-ch-34/

**Languages**
arabic

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by Robonau** [comment] 2020-10-29 07:09
duplicate of #2427

**Closed as completed** 2020-10-29 12:15 UTC
Labels: Duplicate
