### ISSUE TITLE
[Site Request] https://mangayaro.net/

### ISSUE THREAD

**Issue by Shaft14** [manga-download/hakuneko#4945] opened 2022-09-03 07:18 UTC
**Name of the website**
thewebsitename

**Website urls (examples below)**
- Site: https://mangayaro.net/
- Manga List: https://mangayaro.net/manga/
- Manga example: https://mangayaro.net/manga/advanced-evolution/
- Chapter online viewer example: https://mangayaro.net/advanced-evolution-chapter-65-bahasa-indonesia/

**Languages**
Indonesia

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment] 2022-11-12 10:31
Please stop spamming issues for the same website.

Duplicate of https://github.com/manga-download/hakuneko/issues/4718

@Sheepux pls

**Closed as not planned** 2022-11-15 22:42 UTC
Labels: Duplicate
