### ISSUE TITLE
Novelgo

### ISSUE THREAD

**Issue by zenkijoe** [manga-download/hakuneko#2375] opened 2020-09-25 14:01 UTC
**Name of the website**
novelgo

**Website urls (examples below)**
- Site: https://novelgo.id/
- Manga List: https://novelgo.id/novel/
- Manga : https://novelgo.id/novel/ed/
- Chapter online viewer : https://novelgo.id/ed/chapter-1-three-demon-master-1/

**Languages**
indonesian

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by manh21** [comment] 2020-09-28 05:38
Duplicate of #2294

**Closed as completed** 2020-09-28 06:01 UTC
Labels: Duplicate
